# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-12 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IppaUser',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.SmallIntegerField(default=0)),
                ('player_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email_id', models.EmailField(db_index=True, max_length=255)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('password', models.TextField(max_length=255)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('poi_image', models.TextField(blank=True, null=True)),
                ('kyc_status', models.PositiveSmallIntegerField(choices=[(3, 'Not-initiated'), (1, 'Pending'), (0, 'Approved'), (2, 'Declined')], default=3)),
                ('referral_code', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(default='India', max_length=255)),
                ('profile_image', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
