# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-29 17:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0002_auto_20190914_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippauser',
            name='points',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={b'current_points': 0, b'monthly_points': 0, b'redeemable_points': 0, b'redeemed_points': 0, b'total_points': 0}, null=True),
        ),
    ]
