# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-09 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0003_ippauser_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ippauser',
            old_name='kyc_status',
            new_name='poa_status',
        ),
        migrations.AddField(
            model_name='ippauser',
            name='poi_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (0, 'Approved'), (2, 'Declined')], default=3),
        ),
    ]
