# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-15 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0004_auto_20191009_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ippauser',
            name='poa_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='ippauser',
            name='poi_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=255),
        ),
    ]
