# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-09 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0005_auto_20191015_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ippauser',
            name='poa_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Approved'), ('Declined', 'Declined')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ippauser',
            name='poi_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Approved'), ('Declined', 'Declined')], default='', max_length=255),
        ),
    ]
