# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-21 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0006_auto_20191209_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippauser',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ippauser',
            name='kyc_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Approved'), ('Declined', 'Declined')], default='', max_length=255),
        ),
    ]
