# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-30 05:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0007_auto_20200121_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ippauser',
            name='points',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={b'current_month_points': 0, b'last_month_points': 0, b'redeemable_points': 0, b'redeemed_points': 0, b'total_points': 0}, null=True),
        ),
    ]
