# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-29 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('mail_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('subject', models.TextField(verbose_name='Use same variable name in html template and in identifier_dict.')),
                ('mail_body', models.TextField(verbose_name='Use same variable name in html template and in identifier_dict.')),
                ('from_email', models.CharField(default=b'help@ippa.in', max_length=255)),
                ('to_emails', models.TextField(blank=True, null=True)),
                ('cc_emails', models.TextField(blank=True, null=True)),
                ('bcc_emails', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notification_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('notification_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deleated', 'Deleated')], default='Active', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
