# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-29 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NotificationEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='mail',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='NotificationEngine.Mail'),
            preserve_default=False,
        ),
    ]
