# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-30 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotificationEngine', '0003_notificationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='from_email',
            field=models.CharField(default=b'noreply@ippa.in', max_length=255),
        ),
    ]
