# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-09 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchfield',
            name='is_user_filter',
            field=models.BooleanField(default=False),
        ),
    ]
