# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-29 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AccessControl', '0003_ippauser_points'),
        ('Network', '0002_playertag_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('ifsc', models.CharField(blank=True, max_length=11, null=True)),
                ('acc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('acc_number', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Declined', 'Declined')], default='Pending', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bank_account', to='AccessControl.IppaUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('txn_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('txn_date', models.DateTimeField(blank=True, null=True)),
                ('txn_type', models.CharField(choices=[('Withdraw', 'Withdraw'), ('Deposit', 'Deposit')], default='Deposit', max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Failed', 'Failed')], default='Pending', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_txn', to='Network.Network')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_txn', to='AccessControl.IppaUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
