# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-02 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_auto_20191002_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='Transaction.Bank'),
        ),
    ]
