# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-10 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_bankaccount_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_id',
            field=models.CharField(max_length=255),
        ),
    ]