# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-22 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0004_auto_20191010_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='admin_comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='admin_comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]