# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-05-06 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0005_auto_20200122_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank',
        ),
    ]
