# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-29 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertag',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_users', to='Network.Network'),
        ),
    ]
