# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-01 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0002_playertag_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=255),
        ),
    ]
