# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-01 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0003_network_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playertag',
            old_name='tag_name',
            new_name='tag_user_name',
        ),
    ]
