# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-30 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0008_auto_20200430_0516'),
        ('Network', '0004_auto_20191001_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.SmallIntegerField(default=0)),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('txn_type', models.CharField(choices=[('Withdraw', 'Withdraw'), ('Deposit', 'Deposit')], default='Deposit', max_length=255)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_points_networks', to='Network.Network')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_network_points', to='AccessControl.IppaUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
