# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-08-07 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0005_networkpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkpoints',
            name='points',
        ),
        migrations.AddField(
            model_name='networkpoints',
            name='converted_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='networkpoints',
            name='original_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
