# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-08-07 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0006_auto_20200807_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkpoints',
            name='points_earned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
