# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-19 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0004_auto_20191001_2019'),
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.SmallIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('deactivate_date', models.DateTimeField()),
                ('point_name', models.TextField(blank=True, null=True)),
                ('goal_points', models.CharField(blank=True, max_length=255, null=True)),
                ('more_info_link', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Deactive', 'Deactive'), ('Expired', 'Expired')], default='Active', max_length=255)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_reward', to='Network.Network')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
