# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-23 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rewards',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
