# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-26 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0003_auto_20200423_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.SmallIntegerField(default=0)),
                ('redirect_url', models.TextField(blank=True, null=True)),
                ('img_url', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
