# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-06-08 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0009_otp'),
        ('Content', '0005_promotions_tournaments'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemedRewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_date', models.DateTimeField(blank=True, null=True)),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Content.Rewards')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccessControl.IppaUser')),
            ],
        ),
    ]
