# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-09-13 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0007_activity_comments_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent_comment_id',
        ),
    ]
