# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-04-11 08:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0009_otp'),
        ('Content', '0008_remove_comments_parent_comment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.SmallIntegerField(default=0)),
                ('article_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('thumbnail_img_link', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=[], null=True, size=None)),
                ('views_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('upvote_count', models.IntegerField(default=0)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccessControl.IppaUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.SmallIntegerField(default=0)),
                ('group_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Content.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
